### ISSUE TITLE
Compile Fails

### ISSUE THREAD

**Issue by zauberparacelsus** [Hypersomniac/blender-shader#1]
I attempted to compile this using the normal compile instructions for blender, since no Linux builds of this branch were available.  However, one of the steps before compilation fails, thereby preventing me from being able to compile due to missing submodules.

```
git submodule update --init --recursive
```

That command fails, with the following output:

```
zauber@daedalusMK3:~/BUILD/blender-pbr/blender-shader$ git submodule update --init --recursive
Cloning into 'release/datafiles/locale'...
remote: Repository not found.
fatal: repository 'https://github.com/Hypersomniac/blender-translations.git/' not found
Clone of 'https://github.com/Hypersomniac/blender-translations.git' into submodule path 'release/datafiles/locale' failed
```

**Comment by Hypersomniac** [comment]
First, sorry for my late reply.

For your issue I suggest you to clone the main blender master git repo and test to see if everythings compile.
Then erase the sources and replace it with the one of my repository.
Replace only release/scripts and source directories and you should be good to go.

**Comment by zauberparacelsus** [comment]
I finally got around to trying that out and got the compile to start.  However, a little over halfway through the compile I ran into a compile error:

```
/home/zauber/BUILD/blender-pbr/blender-merged/source/blender/gpu/intern/gpu_material.c: In function ‘do_world_tex’:
/home/zauber/BUILD/blender-pbr/blender-merged/source/blender/gpu/intern/gpu_material.c:2362:44: error: too many arguments to function ‘GPU_cube_map’
      GPU_link(mat, "mtex_cube_map", texco, GPU_cube_map(tex->ima, &tex->iuser, false, false), &tin, &trgb);
                                            ^
In file included from /home/zauber/BUILD/blender-pbr/blender-merged/source/blender/gpu/intern/gpu_material.c:65:0:
/home/zauber/BUILD/blender-pbr/blender-merged/source/blender/gpu/GPU_material.h:209:14: note: declared here
 GPUNodeLink *GPU_cube_map(struct Image *ima, struct ImageUser *iuser, bool is_data);
              ^
Building C object source/blender/blenkernel/CMakeFiles/bf_blenkernel.dir/intern/object_dupli.c.o
[ 52%] source/blender/gpu/CMakeFiles/bf_gpu.dir/build.make:415: recipe for target 'source/blender/gpu/CMakeFiles/bf_gpu.dir/intern/gpu_material.c.o' failed
make[2]: *** [source/blender/gpu/CMakeFiles/bf_gpu.dir/intern/gpu_material.c.o] Error 1
CMakeFiles/Makefile2:5110: recipe for target 'source/blender/gpu/CMakeFiles/bf_gpu.dir/all' failed
make[1]: *** [source/blender/gpu/CMakeFiles/bf_gpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

EDIT: In case it matters, the vanilla blender version I used was the latest git master, fe0ca82

**Comment by Hypersomniac** [comment]
Sorry it was typo.

**Comment by zauberparacelsus** [comment]
Alright, thanks.  Gonna try it out now

**Comment by zauberparacelsus** [comment]
Well, that "try it out now" turned into "trying it out three hours later after getting sidetracked by something I was working on"

Anyways, it got compiled all the way to 100%, and then I got over 3000 lines of error spew at the very end of the compile process: http://pastebin.com/qC0XP0kJ

**Comment by zauberparacelsus** [comment]
Previously, I had git cloned blender's master, ran the setup commands, and then copied over blender-shader's source and release/scripts folders into it before running the build.

Now, I am going to try it from a different angle.  Git clone blender's master, and then copy in blender-shader's source and release/scripts folders into it before running the setup commands.  The first command appears to be working, so I'm going to keep my fingers crossed

**Comment by zauberparacelsus** [comment]
Blah.  Same result.

**Comment by zauberparacelsus** [comment]
I don't get this.  I took a quick look at the Windows build instructions (MSVC and MingW), and both require the same git commands to be run.

Can you try building this from a fresh clone?  If you're working off of a copy that originated as a clone of blender's repo, then you'll have (I'm assuming) already ran those commands before having moved to your github repo.  Hence, the problem may have been obscured.

**Comment by Hypersomniac** [comment]
Sorry I can't help you today. I'll investigate tomorrow.

**Comment by zauberparacelsus** [comment]
Alright, thanks.

**Comment by Hypersomniac** [comment]
So you have problems compiling my branch or vanilla blender?

**Comment by zauberparacelsus** [comment]
Your branch.  It fails on the git submodule update command because it is checking github for the various submodules, rather than blender's git server.  Vanilla compiles without any problems.

**Comment by Hypersomniac** [comment]
You need to update the submodules only once with blender's official git. 
Just compile official blender to make sure nothing comes from it.
Then you replaced with my sources (**merge** all the files and folders not only source and release, do not erase any folder) you just need to clean some previous build (delete "linux_build") and recompile with the "make" commande

**Comment by zauberparacelsus** [comment]
Still getting error messages at the end, though not 3300+ lines of them, so I guess that's an improvement.

```
../../lib/libbf_gpu.a(gpu_shader.c.o):gpu_shader.c:function GPU_shader_get_builtin_fx_shader: error: undefined reference to 'datatoc_gpu_shader_fx_colormanage_frag_glsl'
collect2: error: ld returned 1 exit status
source/creator/CMakeFiles/blender.dir/build.make:293: recipe for target 'bin/blender' failed
make[2]: *** [bin/blender] Error 1
CMakeFiles/Makefile2:7007: recipe for target 'source/creator/CMakeFiles/blender.dir/all' failed
make[1]: *** [source/creator/CMakeFiles/blender.dir/all] Error 2
Makefile:146: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Hypersomniac** [comment]
can you make sure the line 
`data_to_c_simple(shaders/gpu_shader_fx_colormanage_frag.glsl SRC)`
is in blender/gpu/CMakeLists.txt ?

**Comment by zauberparacelsus** [comment]
Yes, it is there.

**Comment by Hypersomniac** [comment]
verify that
`extern char datatoc_gpu_shader_fx_colormanage_frag_glsl[];`
is at the top of gpu_shader.c
try also to edit this file (just add a space somewhere where it does not matter.
To force recompiling.
Also what is the error line?

**Comment by zauberparacelsus** [comment]
That's the thing: no line number for any source files were given for the failure.

EDIT: I have restarted the build and will be posting the full output so that you can look through it and see if anything is amiss.

**Comment by zauberparacelsus** [comment]
Okay, here is the build output: http://www.pasteall.org/64159

Normally I'd use pastebin, but they appear to be under heavy load at the moment.

**Comment by Hypersomniac** [comment]
there must be a cache issue.
Is this a clean build? did you delete the entire linux_build folder? I'm sorry I can not help further.

**Comment by zauberparacelsus** [comment]
There was some confusion on my part.  I am now rebuilding with a freshly-generated build folder

**Comment by zauberparacelsus** [comment]
It finally built

**Comment by Hypersomniac** [comment]
Hooray !!

**Comment by zauberparacelsus** [comment]
Thanks for the help!
