### ISSUE TITLE
Any change to world nodetree results in crash

### ISSUE THREAD

**Issue by Viktorsmg** [Hypersomniac/blender-shader#4]
Specs: AMD HD7870 GPU,AMD FX6300 Six-core CPU,8GB RAM,Windows 10.

[Pastebin](http://pastebin.com/bf99xmq5)

Happens when I try to change anything in the world nodetree,not necessarily reducing some brigtness to 0.9.Literally anything-changing a shader,texture,disconnecting things...Even unticking realistic material preview.

It seems to happen with any of my startup files.[Here's one of them.](https://onedrive.live.com/redir?resid=76B5E39F53E2BB47!1498&authkey=!AEUVy3Oy7wjjt3A&ithint=file%2cblend)

Every blend infected with this crashing disease seems to start off with the 3D viewport being empty but everything else has whatever part of the object is visible through it rendered over it.It fills itself when I move around and causing the timeline/other stuff to update clears the part of the scene sitting there.

[Pics of the issue](http://imgur.com/a/Rr36q)

[This one doesn't make a crash.](https://onedrive.live.com/redir?resid=76B5E39F53E2BB47!1572&authkey=!ACUXiNpQqHXWUAQ&ithint=file%2cblend) ([Tutorial](https://www.youtube.com/watch?v=2zd1AI198I8))
It doesn't have any viewport and switching to it has things behaving normally.

Saving a file without realistic material preview tuned on,without an HDRi and either Blender 2.77 or the 0.2.2 build didn't seem to fix it.Grabbing a factory file from 2.68a had it fixed,but only for the file of course.

Adding nodes to the startup file's world nodetree didn't seem to break it.Starting with a broken file didn't break fixed ones and vice-versa.

**Comment by Hypersomniac** [comment]
Thanks for the report man. I experience this issue as well on some scenes only just like you. I'll be investigating!

**Comment by Viktorsmg** [comment]
I have bad news and very good news.

Let's start off with the bad news:The issue doesn't seem to be just nodetree problems. Once a world preview has been rendered, causing a re-render of the 3D viewport or something among those lines will crash Blender. Check the files below for more details..

The very good news: It can be counteracted by hiding the preview. The Cup and cloth,the startup file...They have no world preview. Any other normal Blender file, however, has a world preview, and as such causes these crashes.

[A blend that crashes.](https://onedrive.live.com/redir?resid=76B5E39F53E2BB47!1626&authkey=!AButmHzKpclws-o&ithint=file%2cblend)
[A blend that doesn't crash.](https://onedrive.live.com/redir?resid=76B5E39F53E2BB47!1625&authkey=!ALOZpRv0_GHHBzE&ithint=file%2cblend)

**Comment by Hypersomniac** [comment]
Should be Fixed by c112a54d2a992399f742dd5310e84aad905d400b
