### ISSUE TITLE
Realistic Material Preview Does not work for glossy shader, etc. on Mac

### ISSUE THREAD

**Issue by Kanen31** [Hypersomniac/blender-shader#5]
Terminal readout when glossy shader is used with realistic material preview:
"found bundled python: /Applications/Blender_PBR_v2/Blender PBR 2.app/Contents/MacOS/../Resources/2.77/pythonGPUShader: compile error:
ERROR: 0:98: 'switch' : Reserved word. 
ERROR: 0:98: 'switch' : syntax error: syntax error

Unable to create a GPUShader for builtin shader: 11"

**Comment by Hypersomniac** [comment]
This was fixed by 80f03704e771fce3132536f778187a23d71607bc
